apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  BACKEND_URL: "http://todo-backend-svc:3005"
  IMAGE_PATH: "/usr/src/app/files/image.jpg"
  PICSUM_URL: "https://picsum.photos/1200"
  PORT: "3000"